# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7959415285120679504fa35032a719fd821e49dd1eb7e625582640a0e88a180e44325804d51a9e71d554c6948a74ca7ac53d2cbc19e64cefe3f47bc8b0ace2d

test:
  secret_key_base: d7de548352b7cfe39bffd1e1690cba7fd1a4b0e9a6e737ae85bad52b8dc9fe50d1caac595a1bfb52b11c8ff14398a6bd0611d0782cf018a8cb1841b3442a1fa3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
